---
- hosts: apache-server
  become: yes
  vars_files:
        - ./vars/main.yml
  roles:
  - ./roles/filebeat_configure
- hosts: elk-server
  become: yes
  vars_files:
        - ./vars/main.yml
  roles:
  - ./roles/apache_syslog
    #- hosts: elk-server
    #become: yes
    #vars_files:
#        - ./vars/main.yml
#  roles:
#  - ./roles/check_index

