---
- hosts: jenkins
  become: yes
  vars_files:
        - ./vars/main.yml
  roles:
  - ./roles/filebeat_configure
- hosts: elk-server
  become: yes
  vars_files:
        - ./vars/main.yml
  roles:
  - ./roles/jenkins_syslog

