####################
- name: Playbook
  hosts: zabbix_end
  become: yes
  become_user: root
  vars:
    #mysql_root_password: password
  tasks:
       - name: install mysql server
         apt:
          name: mysql-server
          state: present
       - name: install client mysql
         apt:
          name: mysql-client
          state: present
       - name: Update apt-get repo and cache
         apt: update_cache=yes force_apt_get=yes
