- name: Playbook
  hosts: zabbix_end
  become: yes
  become_user: root
  tasks:
    # - name: Ensure SELinux is set to enforcing mode
    #lineinfile:
    # path: /etc/zabbix/zabbix_server.conf
      # regexp: '^#DBPassword:'
      # line: 'DBPassword:password'
  - name: Build zcat
    become: yes
    archive:
      path: usr/share/zabbix-sql-scripts/mysql/server.sql.gz
      dest:  mysql --default-character-set=utf8mb4 -uzabbix -p zabbix
  - name: Ensure SELinux is set to enforcing mode
    lineinfile:
     path: /etc/zabbix/zabbix_server.conf
      # regexp: '^#DBPassword:'
     line: 'DBPassword:password'


