- name: maven installation
  hosts: apache_ub
  become: yes
  become_user: root
  tasks:
    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes
    - name: install apache
      apt:
        name: apache2
        state: present
    - name: activating 
      become: yes
      command: "systemctl is-active apache2"
    - name: enabaling
      become: yes
      command: "systemctl is-enabled apache2"
    - name: Allow all access to tcp port 80
      ufw:
       rule: allow
       port: '80'
       proto: tcp
    - name: allow port
      ufw: 
        rule: allow
        port: 443
        proto: tcp
