- name: Playbook
  hosts: test1
  become: yes
  become_user: root
  tasks:
        - name: Install OpenJDK Java
          become: yes
          apt:
           name: "{{ item }}"
           state: present
          with_items:
            openjdk-11-jdk 
        - name: postgresql key
          apt_key:
            url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
            state: present
          become: true

        - name: create variable
          #sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" >> /etc/apt/sources.list.d/pgdg.list'
          command: bash -c "echo \"deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main\" "
          register: repo_line

            # - debug:
            # msg: "{{ repo_line.stdout }}"

        - name: add postgresql repo
          apt_repository:
            repo: "{{ repo_line.stdout }}"
            state: present
          become: true


        - name: install postgresql
          apt:
           name: postgresql 
           state: present
           update_cache: yes
          become: true

        - name: install postgresql
          apt:
           name: postgresql-contrib
           state: present
           update_cache: yes
          become: true
         
        
        - name: enable  service
          become: yes
          command: "systemctl enable postgresql"
        - name: start  service
          become: yes
          command: "systemctl start postgresql"
