- name: Playbook
  hosts: zabbix_rh
  become: yes
  become_user: root
  tasks:
       - name: Install repos
         yum:
           name: https://repo.zabbix.com/zabbix/6.2/rhel/6/x86_64/zabbix-release-6.2-3.el6.noarch.rpm
           state: present
             # - name: cleanall
             #yum:
             # name: clean
             #state: present
       - name: install agent
         yum:
           name: zabbix-agent
           state: present
       - name: restart  service
         become: yes
         command: "systemctl restart zabbix-agent"
       - name: enable  service
         become: yes
         command: "systemctl enable zabbix-agent"
