- name: Playbook
  hosts: zabbix_rh
  become: yes
  become_user: root
  vars:
    # mysql_root_password: password
  tasks:
       - name: install mysql server
         yum:
          name: mysql-server
          state: present
       - name: install client mysql
         yum:
          name: mysql-client
          state: present
       - name: Update  repo and cache
         yum: update_cache=yes 

