- name: Playbook
  hosts: zabbix_rh
  become: yes
  become_user: root
  tasks:
    #  - name: install zabbix 6.x rpm repository
         # yum_repository:
           # name: zabbix-6.x
             # description: zabbix repository for 6.x packages
             # baseurl: https://repo.zabbix.com/zabbix/6.0/rhel/9/x86_64/zabbix-release-6.0-4.el9.noarch.rpm
             # gpgcheck: true
             #   gpgkey: http://repo.zabbix.com/RPM-GPG-KEY-ZABBIX-A14FE591
             # become: true
    #   - name: Install repos
    #    ansible.builtin.yum:
    #      name: https://repo.zabbix.com/zabbix/6.0/rhel/9/x86_64/zabbix-release-6.0-4.el9.noarch.rpm
    #      state: present
             # - name: package
             #yum:
             #dpkg_options: dpkg -i zabbix-release_6.2-2+ubuntu22.04_all.deb
       - name: Install repos
         ansible.builtin.yum:
          name: https://repo.zabbix.com/zabbix/6.0/rhel/9/x86_64/zabbix-release-6.0-4.el9.noarch.rpm
          state: present

       - name: Update  repo and cache
         yum: update_cache=yes 
       - name: install zabbix server
         yum:
          name: zabbix-server-mysql
          state: present
       - name: install zabbix mysql
         yum:
          name: zabbix-web-mysql
          state: present
       - name: install zabbix apache
         yum:
          name: zabbix-apache-conf
          state: present
       - name: install zabbix sql
         yum:
          name: zabbix-sql-scripts
          state: present
       - name: zabbix policy
         yum:
          name: zabbix-selinux-policy
          state: present

            #   - name: Build zcat
            # become: yes
            # archive:
            # path: usr/share/zabbix-sql-scripts/mysql/server.sql.gz
            #dest:  mysql --default-character-set=utf8mb4 -uzabbix -p zabbix
            # format: gz

