---
# tasks file for logstash_install   
- name: Enable the plugin
  jenkins_plugin:
     name: Logstash
     url_username: "{{ jenkins_user }}"
     url_password: "{{ jenkins_password }}"
- name: Logstash plugin configuration
  template:
     src: ../templates/jenkins.plugins.logstash.LogstashConfiguration.xml
     dest: /var/lib/jenkins
- name: Restart Jenkins if required
  service:
     name: jenkins
     state: restarted

